/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  // The app toggles `.theme-dark` on <html> (see OrbitContext), not the
  // Tailwind-default `.dark` — point dark: variants at the real class so they
  // actually activate instead of silently never matching.
  darkMode: ['selector', '.theme-dark'],
  theme: {
    extend: {
      colors: {
        // Legacy apple tokens (kept for backward compat)
        apple: {
          blue: 'var(--accent-blue)',
          green: 'var(--accent-green)',
          red: 'var(--accent-red)',
          purple: 'var(--accent-purple)',
        },
        // Stitch / Material Design 3 tokens
        'primary': '#0058bc',
        'on-primary': '#ffffff',
        'primary-container': '#0070eb',
        'on-primary-container': '#fefcff',
        'primary-fixed': '#d8e2ff',
        'primary-fixed-dim': '#adc6ff',
        'on-primary-fixed': '#001a41',
        'on-primary-fixed-variant': '#004493',
        'inverse-primary': '#adc6ff',
        'surface-tint': '#005bc1',
        'secondary': '#5d5e63',
        'on-secondary': '#ffffff',
        'secondary-container': '#dfdfe4',
        'on-secondary-container': '#616267',
        'secondary-fixed': '#e2e2e7',
        'secondary-fixed-dim': '#c6c6cb',
        'on-secondary-fixed': '#1a1c1f',
        'on-secondary-fixed-variant': '#45474b',
        'tertiary': '#9e3d00',
        'on-tertiary': '#ffffff',
        'tertiary-container': '#c64f00',
        'on-tertiary-container': '#fffbff',
        'tertiary-fixed': '#ffdbcc',
        'tertiary-fixed-dim': '#ffb595',
        'on-tertiary-fixed': '#351000',
        'on-tertiary-fixed-variant': '#7c2e00',
        'error': '#ba1a1a',
        'on-error': '#ffffff',
        'error-container': '#ffdad6',
        'on-error-container': '#93000a',
        'surface': '#faf9fe',
        'on-surface': '#1a1b1f',
        'surface-variant': '#e3e2e7',
        'on-surface-variant': '#414755',
        'surface-container-lowest': '#ffffff',
        'surface-container-low': '#f4f3f8',
        'surface-container': '#eeedf3',
        'surface-container-high': '#e9e7ed',
        'surface-container-highest': '#e3e2e7',
        'surface-dim': '#dad9df',
        'surface-bright': '#faf9fe',
        'inverse-surface': '#2f3034',
        'inverse-on-surface': '#f1f0f5',
        'background': '#faf9fe',
        'on-background': '#1a1b1f',
        'outline': '#717786',
        'outline-variant': '#c1c6d7',
      },
      spacing: {
        'stack-sm': '8px',
        'stack-md': '16px',
        'stack-lg': '24px',
        'margin-page': '20px',
        'gutter-grid': '12px',
      },
      borderRadius: {
        DEFAULT: '1rem',
        'lg': '2rem',
        'xl': '3rem',
        'full': '9999px',
        'glass': '24px',
      },
      fontFamily: {
        'sans': ['Inter', 'Outfit', 'sans-serif'],
        'body-base': ['Inter', 'sans-serif'],
        'headline-md': ['Inter', 'sans-serif'],
        'display-lg': ['Inter', 'sans-serif'],
        'label-xs': ['Inter', 'sans-serif'],
        'label-sm': ['Inter', 'sans-serif'],
      },
      fontSize: {
        'body-base': ['17px', { lineHeight: '22px', letterSpacing: '-0.2px', fontWeight: '400' }],
        'headline-md': ['22px', { lineHeight: '28px', letterSpacing: '-0.3px', fontWeight: '600' }],
        'display-lg': ['34px', { lineHeight: '41px', letterSpacing: '-0.5px', fontWeight: '700' }],
        'label-xs': ['11px', { lineHeight: '13px', letterSpacing: '0.06em', fontWeight: '600' }],
        'label-sm': ['13px', { lineHeight: '18px', letterSpacing: '0px', fontWeight: '500' }],
      },
      backdropBlur: {
        'glass': 'var(--glass-blur)',
      }
    },
  },
  plugins: [],
}
